In [21]:
import pandas as pd
import json

In [8]:
competitions = pd.read_json("data/competitions.json")

pl = competitions[competitions["competition_id"] == 11]
pl[["competition_name", "season_name", "season_id"]]

   competition_name season_name  season_id
38          La Liga   2020/2021         90
39          La Liga   2019/2020         42
40          La Liga   2018/2019          4
41          La Liga   2017/2018          1
42          La Liga   2016/2017          2
43          La Liga   2015/2016         27
44          La Liga   2014/2015         26
45          La Liga   2013/2014         25
46          La Liga   2012/2013         24
47          La Liga   2011/2012         23
48          La Liga   2010/2011         22
49          La Liga   2009/2010         21
50          La Liga   2008/2009         41
51          La Liga   2007/2008         40
52          La Liga   2006/2007         39
53          La Liga   2005/2006         38
54          La Liga   2004/2005         37
55          La Liga   1973/1974        278

In [3]:
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,NaN,NaN,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,NaN,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [7]:
competitions[competitions["competition_id"] == 11].season_name.unique()

<StringArray>
['2020/2021', '2019/2020', '2018/2019', '2017/2018', '2016/2017', '2015/2016',
 '2014/2015', '2013/2014', '2012/2013', '2011/2012', '2010/2011', '2009/2010',
 '2008/2009', '2007/2008', '2006/2007', '2005/2006', '2004/2005', '1973/1974']
Length: 18, dtype: str

In [6]:
competitions[['competition_id', 'competition_name']].drop_duplicates().sort_values(by='competition_id')

    competition_id         competition_name
64               2           Premier League
58               7                  Ligue 1
0                9            1. Bundesliga
38              11                  La Liga
66              12                  Serie A
3               16         Champions League
70              35       UEFA Europa League
25              37  FA Women's Super League
29              43           FIFA World Cup
61              44      Major League Soccer
63              49                     NWSL
71              53        UEFA Women's Euro
68              55                UEFA Euro
73              72        Women's World Cup
56              81         Liga Profesional
22              87             Copa del Rey
62             116    North American League
21             223             Copa America
37            1238      Indian Super league
2             1267   African Cup of Nations
28            1470       FIFA U20 World Cup

## La liga 2017/18

In [10]:
la_liga_17_18 = pd.read_json("data/la_liga_2017_18.json")

In [11]:
la_liga_17_18.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,9880,2018-04-14,16:15:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 1, 'season_name': '2017/2018'}","{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 207, 'away_team_name': 'Valen...",2,1,available,scheduled,2023-02-08T17:23:53.901920,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",32,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...","{'id': 2728, 'name': 'Carlos del Cerro Grande'..."
1,9912,2018-04-29,20:45:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 1, 'season_name': '2017/2018'}","{'home_team_id': 219, 'home_team_name': 'RC De...","{'away_team_id': 217, 'away_team_name': 'Barce...",2,4,available,scheduled,2022-12-05T14:42:44.641092,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",35,"{'id': 1, 'name': 'Regular Season'}","{'id': 4658, 'name': 'Estadio Abanca-Riazor', ...","{'id': 2602, 'name': 'Ricardo De Burgos Bengoe..."
2,9924,2018-05-06,20:45:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 1, 'season_name': '2017/2018'}","{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 220, 'away_team_name': 'Real ...",2,2,available,scheduled,2022-12-01T03:25:12.063586,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",36,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...","{'id': 2608, 'name': 'Alejandro José Hernández..."
3,9855,2018-03-18,16:15:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 1, 'season_name': '2017/2018'}","{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 215, 'away_team_name': 'Athle...",2,0,available,scheduled,2022-12-01T02:33:31.178193,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",29,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...","{'id': 2575, 'name': 'Santiago Jaime Latre', '..."
4,9827,2018-03-01,21:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 1, 'season_name': '2017/2018'}","{'home_team_id': 208, 'home_team_name': 'Las P...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,1,available,scheduled,2022-08-04T17:18:06.540844,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",26,"{'id': 1, 'name': 'Regular Season'}","{'id': 357, 'name': 'Estadio de Gran Canaria',...","{'id': 180, 'name': 'Antonio Miguel Mateu Laho..."

In [12]:
la_liga_17_18.shape

(36, 18)

In [31]:
for x in la_liga_17_18[["match_id"]]["match_id"].to_list():
    print(x, end=" ")

9880 9912 9924 9855 9827 9799 9636 9609 9575 9928 9736 9742 9765 9661 9592 9870 9783 9700 9860 9695 9794 9717 9673 9650 9620 9837 9811 9642 9774 9602 9948 9682 9581 9726 9754 9889

In [24]:
match_id = "match_1_info"

shots = []

for match_id in la_liga_17_18["match_id"]:
    with open(f"data/events/{match_id}.json") as f:
        events = json.load(f)
        for e in events:
            if e["type"]["name"] == "Shot":
                shots.append(e)

shots_df = pd.json_normalize(shots)

In [25]:
shots_df.shape

(971, 46)

In [37]:
shots_df.head()

,id,index,period,timestamp,minute,second,possession,location,duration,related_events,...,shot.saved_to_post,under_pressure,shot.aerial_won,out,shot.one_on_one,shot.open_goal,shot.saved_off_target,shot.redirect,shot.follows_dribble,off_camera
0,2258c11c-0916-4976-bfde-a66e89ffeb8d,191,1,00:03:31.114,3,31,10,"[101.0, 21.3]",1.020612,[12f35fe0-b936-439e-8087-0777a7dc8a38],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,f0be7ddf-1e01-4315-aee1-8d5fda52a739,383,1,00:07:02.539,7,2,14,"[103.9, 28.4]",0.127392,"[0638e39d-d8b2-4364-805e-109a33238e0f, 55518d2...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bb173d27-76c4-4044-b883-8bd6f8450cf2,654,1,00:13:21.294,13,21,25,"[112.5, 26.0]",0.263821,[6c0ad8df-aad9-4e24-aaa9-3a27d8736dfd],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7b02c827-3580-4149-9912-216ce2bd544f,700,1,00:14:07.045,14,7,26,"[113.2, 46.0]",0.336449,[ac01843e-3a1a-41de-8090-5cd3e311806f],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3b15d864-8738-4cb1-8275-f94277570223,837,1,00:17:27.953,17,27,31,"[92.8, 32.9]",0.155997,"[2a4a1d74-f213-4ac3-b223-12b8507019c4, e29e5ae...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
shots_df.head()
for x in shots_df.columns:
    print(x, end=", ")

id, index, period, timestamp, minute, second, possession, location, duration, related_events, type.id, type.name, possession_team.id, possession_team.name, play_pattern.id, play_pattern.name, team.id, team.name, player.id, player.name, position.id, position.name, shot.statsbomb_xg, shot.end_location, shot.key_pass_id, shot.body_part.id, shot.body_part.name, shot.type.id, shot.type.name, shot.outcome.id, shot.outcome.name, shot.technique.id, shot.technique.name, shot.freeze_frame, shot.first_time, shot.deflected, shot.saved_to_post, under_pressure, shot.aerial_won, out, shot.one_on_one, shot.open_goal, shot.saved_off_target, shot.redirect, shot.follows_dribble, off_camera,

In [38]:
shots_df.to_json("final_df.json")